import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import page from "./page";

import Link from "next/link";

import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body>
        <Header />
        {/* Links */}
        <nav>
          <ul>
            <li>
              <Link href="/produtos">Produtos</Link>
            </li>
            <li>
              <Link href="/tecnologias">Tecnologias</Link>
            </li>
          </ul>
        </nav>
        <main className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
